# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
use_frameworks!

target 'editorTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  # Pods for editorTest
  pod 'iOSPhotoEditor', :git => 'https://github.com/dolzhenko-tony/photo-editor.git'

end
